filterocs wg. Henne-Ei-Problem entfernt

diff --git a/src/om/scripts/ocs b/src/om/scripts/ocs
--- a/src/om/scripts/ocs
+++ b/src/om/scripts/ocs
@@ -1,5 +1,5 @@
 #!/bin/sh
-# $Header: /home/florenz/opal/home_uebb_CVS/CVS/ocs/src/om/scripts/ocs,v 1.4 1999-09-17 12:25:07 kd Exp $
+# $Header: /home/florenz/opal/home_uebb_CVS/CVS/ocs/src/om/scripts/ocs,v 1.5 1999-09-17 14:06:34 kd Exp $
 
 SHELL=/bin/sh
 export SHELL
@@ -364,8 +364,7 @@ fi
 if [ -r "$sysdefs" ] 
 then
     (${XGMAKE} -f $OCSOM/make/Makefile.develop \
-	 "SYSDEFS=$sysdefs" $makeflags $target 2>&1 || echo "+++failure+++"; exit 9) \
-    | ${OCSOM}/etc/filterocs $target
+	 "SYSDEFS=$sysdefs" $makeflags $target 2>&1 || echo "+++failure+++"; exit 9)
 else
   ${ECHO} "No file \`SysDefs' and no system definition on command line"
   exit 127
