letzte Fehler beseitigt, neue Funktion pcheck-info

diff --git a/src/om/scripts/ocs b/src/om/scripts/ocs
--- a/src/om/scripts/ocs
+++ b/src/om/scripts/ocs
@@ -1,5 +1,5 @@
 #!/bin/sh
-# $Header: /home/florenz/opal/home_uebb_CVS/CVS/ocs/src/om/scripts/ocs,v 1.8 2000-06-08 11:56:52 kd Exp $
+# $Header: /home/florenz/opal/home_uebb_CVS/CVS/ocs/src/om/scripts/ocs,v 1.9 2000-06-09 12:21:10 kd Exp $
 
 SHELL=/bin/sh
 export SHELL
@@ -370,8 +370,10 @@ fi
 
 if [ -r "$sysdefs" ] 
 then
-    ${XGMAKE} -f $OCSOM/make/Makefile.develop \
-	 "SYSDEFS=$sysdefs" $makeflags $target 2>&1 || echo "+++failure+++"; exit 9
+    (${XGMAKE} -f $OCSOM/make/Makefile.develop \
+	 "SYSDEFS=$sysdefs" $makeflags $target 2>&1 || \
+	    (echo "+++failure+++"; exit 9)); status=$?
+    
 else
   ${ECHO} "No file \`SysDefs' and no system definition on command line"
   exit 127
