in ocs/examples: SysDefs aufgeräumt kleine Sachen in src/lib/Tools/Java Kleinigkeiten an Skripten configure an javacc, pizza etc. angepaßt

diff --git a/src/om/scripts/ocsadmin b/src/om/scripts/ocsadmin
--- a/src/om/scripts/ocsadmin
+++ b/src/om/scripts/ocsadmin
@@ -1,5 +1,5 @@
 #! /bin/sh
-# $Header: /home/florenz/opal/home_uebb_CVS/CVS/ocs/src/om/scripts/ocsadmin,v 1.7 1999-10-13 13:46:54 kd Exp $
+# $Header: /home/florenz/opal/home_uebb_CVS/CVS/ocs/src/om/scripts/ocsadmin,v 1.8 1999-10-21 13:56:16 kd Exp $
 
 ## initialise SHELL
 SHELL=/bin/sh
@@ -195,11 +195,18 @@ if [ "$1" = "init" ]; then
       SED=sed ;
     fi
     export SED
-    mkdir $OCSHOME
-    ok=$?
-    if [ "$ok" != "0" ]; then
-	echo "cannot create $OCSHOME"
-	exit 2
+    if [ "$1" = "reinit" ]; then
+      if [ ! -d "$OCSHOME" ]; then
+        echo "directory $OCSHOME does not exist -- use make install to create"
+      fi
+    else
+      mkdir $OCSHOME
+      ok=$?
+      if [ "$ok" != "0" ]; then
+	  echo "cannot create $OCSHOME"
+	  echo "use make reinstall for installation into existing directory"
+  	  exit 2
+      fi
     fi
     SpecsDir=no
     for s in $OCSSPECS
@@ -281,7 +288,7 @@ case "$1" in
 			# echo "evaluating >$PKGPREHOOK<"
 			eval $PKGPREHOOK
 			if [ -z "$PKGHOOK" ]; then
-			    echo "PKGHOOK is empty"
+			    # echo "PKGHOOK is empty"
 			    ocs $PKGOCSFLAGS install
 			else    
 			    # echo "evaluating PKGHOOK >$PKGHOOK<"
