Option to update inter fils in ocsadmin

diff --git a/src/om/scripts/ocsadmin b/src/om/scripts/ocsadmin
--- a/src/om/scripts/ocsadmin
+++ b/src/om/scripts/ocsadmin
@@ -11,24 +11,24 @@ SourceSpecs() {
     ok=no
     for d in $OCSSPECS 
     do
-#	echo "trying $d/$OSARCH/ShSpecs.$1 $d/$OSARCH/Specs.$1 $d/ShSpecs.$1 $d/Specs.$1"
-	if [ -f "$d/$OSARCH/ShSpecs.$1" ] ; then
-	    . $d/$OSARCH/ShSpecs.$1; ok=yes; break;
-	elif [ -f "$d/$OSARCH/Specs.$1" ] ; then
-	    $OCSHOME/lib/om/etc/gmake2sh < $d/$OSARCH/Specs.$1 > /tmp/gmake2sh.$$
-	    . /tmp/gmake2sh.$$
-	    $RM /tmp/gmake2sh.$$
-	    ok=yes
-	    break
-	elif [ -f "$d/ShSpecs.$1" ]; then
-	    . "$d/ShSpecs.$1"; ok=yes; break;
-	elif [ -f "$d/Specs.$1" ]; then
-	    $OCSHOME/lib/om/etc/gmake2sh < $d/Specs.$1 > /tmp/gmake2sh.$$
-	    . /tmp/gmake2sh.$$
-	    $RM /tmp/gmake2sh.$$
-	    ok=yes
-	    break
-	fi  
+#       echo "trying $d/$OSARCH/ShSpecs.$1 $d/$OSARCH/Specs.$1 $d/ShSpecs.$1 $d/Specs.$1"
+        if [ -f "$d/$OSARCH/ShSpecs.$1" ] ; then
+            . $d/$OSARCH/ShSpecs.$1; ok=yes; break;
+        elif [ -f "$d/$OSARCH/Specs.$1" ] ; then
+            $OCSHOME/lib/om/etc/gmake2sh < $d/$OSARCH/Specs.$1 > /tmp/gmake2sh.$$
+            . /tmp/gmake2sh.$$
+            $RM /tmp/gmake2sh.$$
+            ok=yes
+            break
+        elif [ -f "$d/ShSpecs.$1" ]; then
+            . "$d/ShSpecs.$1"; ok=yes; break;
+        elif [ -f "$d/Specs.$1" ]; then
+            $OCSHOME/lib/om/etc/gmake2sh < $d/Specs.$1 > /tmp/gmake2sh.$$
+            . /tmp/gmake2sh.$$
+            $RM /tmp/gmake2sh.$$
+            ok=yes
+            break
+        fi  
     done
     if [ $ok = no ]; then
        echo "+++ cannot find ShSpecs.$1 or Specs.$1 in $OCSSPECS"
@@ -42,19 +42,19 @@ CheckRequireds() {
     do
       if [ ! -f "$OCSHOME/packages/$r" ]; then
         if [ -n "$PKGNAME" ]; then
-	    echo "+++ package $PKGNAME requires $r"
-	fi
+            echo "+++ package $PKGNAME requires $r"
+        fi
         if [ -n "$LIBNAME" ]; then
-	    echo "+++ library $LIBNAME requires $r"
-	fi
-	ok="no"
+            echo "+++ library $LIBNAME requires $r"
+        fi
+        ok="no"
       fi
     done
     if [ $ok = "no" ]; then 
-	exit 4;
+        exit 4;
     fi
 }
-	
+        
 
 ## initialise standard OCS variables
 if [ -z "$OCS" ] 
@@ -156,26 +156,26 @@ ok=`echo $1 | grep '-'`
 if [ -n "$ok" ]; then
   case $1 in
     -ocssrc)
-	shift
-	OCSSRC="$1"
-	OCSETC="$OCSSRC/om/etc"
-	shift ;;
+        shift
+        OCSSRC="$1"
+        OCSETC="$OCSSRC/om/etc"
+        shift ;;
     -ocshome)
-	shift
-	OCSHOME="$1"
-	shift ;;
+        shift
+        OCSHOME="$1"
+        shift ;;
     -ocsetc)
-	shift
-	OCSETC="$1"
-	shift ;;
+        shift
+        OCSETC="$1"
+        shift ;;
     -ocsspecs)
-	shift
-	OCSSPECS="$OCSSPECS $1"
-	shift;;
+        shift
+        OCSSPECS="$OCSSPECS $1"
+        shift;;
     *)
-	echo "Unknown option $1" 
-	usage
-	exit 1;;
+        echo "Unknown option $1" 
+        usage
+        exit 1;;
   esac
 fi
 done
@@ -198,7 +198,7 @@ if [ "$1" = "init" ]; then
     if [ "$1" = "reinit" ]; then
       if [ ! -d "$OCSHOME" ]; then
         echo "directory $OCSHOME does not exist -- use make install to create"
-	exit 2
+        exit 2
       fi
       shift
     else
@@ -206,35 +206,35 @@ if [ "$1" = "init" ]; then
         mkdir $OCSHOME
         ok=$?
         if [ "$ok" != "0" ]; then
-	    echo "cannot create $OCSHOME"
-  	    exit 2
+            echo "cannot create $OCSHOME"
+            exit 2
         fi
       else
         if [ ! -w "$OCSHOME" ]; then
           echo "$OCSHOME exists, but is not writeable"
-	  exit 2
+          exit 2
         fi
-	checkdir=`ls $OCSHOME`
-	if [ -n "$checkdir" ]; then
-	  echo "$OCSHOME is not empty. Use make reinstall"
-	  exit 2
-	fi
+        checkdir=`ls $OCSHOME`
+        if [ -n "$checkdir" ]; then
+          echo "$OCSHOME is not empty. Use make reinstall"
+          exit 2
+        fi
       fi
     fi
     SpecsDir=no
     for s in $OCSSPECS
     do
-	if [ -f "$s/Specs.basic" ]; then
-	    SpecsDir=$s
-	fi
+        if [ -f "$s/Specs.basic" ]; then
+            SpecsDir=$s
+        fi
     done
     if [ "$SpecsDir" = no ]; then
-	echo "Specs.basic not found in $OCSSPECS"
-	exit 2
+        echo "Specs.basic not found in $OCSSPECS"
+        exit 2
     fi
     if [ ! -f "$OCSETC/gmake2sh" ]; then
-	echo "cannot find $OCSETC/gmake2sh"
-	exit 2
+        echo "cannot find $OCSETC/gmake2sh"
+        exit 2
     fi
     for d in $OCSHOME/bin $OCSHOME/lib $OCSHOME/lib/opal_base $OCSHOME/lib/om $OCSHOME/lib/om/etc $OCSHOME/lib/om/specs $OCSHOME/lib/om/make $OCSHOME/packages $OCSHOME/man $OCSHOME/man/man1
     do
@@ -264,69 +264,68 @@ SpecsDir=no
 for s in $OCSSPECS
 do
     if [ -f $s/ShSpecs.basic ]; then
-	. $s/ShSpecs.basic
+        . $s/ShSpecs.basic
     fi
 done
 
 ## now interpret commands
-
 case "$1" in
     install)
-	shift
-	INSTALLBINPATH=$OCSHOME/bin; export INSTALLBINPATH
-	INSTALLDOCPATH=$OCSHOME/doc; export INSTALLDOCPATH
-	INSTALLLIBPATH=$OCSHOME/lib; export INSTALLLIBPATH
-	INSTALLMANPATH=$OCSHOME/man; export INSTALLMANPATH
-	INSTALLBINFLAGS="-s -m 0555 -dm 0755"; export INSTALLBINFLAGS
-	INSTALLDOCFLAGS="-m 0444 -dm 0755"; export INSTALLDOCFLAGS
-	INSTALLLIBFLAGS="-m 0444 -dm 0755"; export INSTALLLIBFLAGS
-	INSTALLMANFLAGS="-m 0444 -dm 0755"; export INSTALLMANFLAGS
-	PATH=$OCSHOME/bin:$PATH; export PATH
-	while [ -n "$1" ]
-	do
-	    SourceSpecs $1
-	    CheckRequireds
-	    case "$1" in
-		lib.*)
-		    $ECHO "Installing library $1 ..."
-		    $OCSOM/etc/genshlib -v $LIBVERSION -d "${LIBDEPS}" ${LIBSYSTEMS} ${LIBDIR}
-		    # echo "now evaluating :${LIBHOOK}:"
-		    eval ${LIBHOOK}
-		    echo "ready"
-		    echo library: $LIBDESCR > $OCSHOME/packages/$1
-		    echo version: $LIBVERSION >> $OCSHOME/packages/$1
-		    echo installed `date` >> $OCSHOME/packages/$1
-		    shift 
-		    ;;
-		pkg.*)
-		    $ECHO "Installing package $1 ..."
-		    (   cd $PKGBASE
-			# echo "INSTALLBINPATH is $INSTALLBINPATH"
-			# echo "evaluating >$PKGPREHOOK<"
-			eval $PKGPREHOOK
-			if [ -z "$PKGHOOK" ]; then
-			    # echo "PKGHOOK is empty"
-			    ocs $PKGOCSFLAGS install
-			else    
-			    # echo "evaluating PKGHOOK >$PKGHOOK<"
-			    eval $PKGHOOK
-			fi
-			if [ -n "$PKGPOSTHOOK" ]; then
-			    # echo "evaluating PKGPOSTHOOK >$PKGPOSTHOOK<"
-			    eval $PKGPOSTHOOK
-			fi
-		    )
-		    echo package: $PKGDESCR > $OCSHOME/packages/$1
-		    echo version: $PKGVERSION >> $OCSHOME/packages/$1
-		    echo installed `date` >> $OCSHOME/packages/$1
-		    shift
-		    ;;    
-		*)
-		    $ECHO "don't know how to install $1"
-		    exit 1
-	    esac
-	done
-	;;
+        shift
+        INSTALLBINPATH=$OCSHOME/bin; export INSTALLBINPATH
+        INSTALLDOCPATH=$OCSHOME/doc; export INSTALLDOCPATH
+        INSTALLLIBPATH=$OCSHOME/lib; export INSTALLLIBPATH
+        INSTALLMANPATH=$OCSHOME/man; export INSTALLMANPATH
+        INSTALLBINFLAGS="-s -m 0555 -dm 0755"; export INSTALLBINFLAGS
+        INSTALLDOCFLAGS="-m 0444 -dm 0755"; export INSTALLDOCFLAGS
+        INSTALLLIBFLAGS="-m 0444 -dm 0755"; export INSTALLLIBFLAGS
+        INSTALLMANFLAGS="-m 0444 -dm 0755"; export INSTALLMANFLAGS
+        PATH=$OCSHOME/bin:$PATH; export PATH
+        while [ -n "$1" ]
+        do
+            SourceSpecs $1
+            CheckRequireds
+            case "$1" in
+                lib.*)
+                    $ECHO "Installing library $1 ..."
+                    $OCSOM/etc/genshlib -v $LIBVERSION -d "${LIBDEPS}" ${LIBSYSTEMS} ${LIBDIR}
+                    # echo "now evaluating :${LIBHOOK}:"
+                    eval ${LIBHOOK}
+                    echo "ready"
+                    echo library: $LIBDESCR > $OCSHOME/packages/$1
+                    echo version: $LIBVERSION >> $OCSHOME/packages/$1
+                    echo installed `date` >> $OCSHOME/packages/$1
+                    shift 
+                    ;;
+                pkg.*)
+                    $ECHO "Installing package $1 ..."
+                    (   cd $PKGBASE
+                        # echo "INSTALLBINPATH is $INSTALLBINPATH"
+                        # echo "evaluating >$PKGPREHOOK<"
+                        eval $PKGPREHOOK
+                        if [ -z "$PKGHOOK" ]; then
+                            # echo "PKGHOOK is empty"
+                            ocs $PKGOCSFLAGS install
+                        else    
+                            # echo "evaluating PKGHOOK >$PKGHOOK<"
+                            eval $PKGHOOK
+                        fi
+                        if [ -n "$PKGPOSTHOOK" ]; then
+                            # echo "evaluating PKGPOSTHOOK >$PKGPOSTHOOK<"
+                            eval $PKGPOSTHOOK
+                        fi
+                    )
+                    echo package: $PKGDESCR > $OCSHOME/packages/$1
+                    echo version: $PKGVERSION >> $OCSHOME/packages/$1
+                    echo installed `date` >> $OCSHOME/packages/$1
+                    shift
+                    ;;    
+                *)
+                    $ECHO "don't know how to install $1"
+                    exit 1
+            esac
+        done
+        ;;
     info)
       echo "The following packages are installed: "
       echo `$LS $OCSHOME/packages/* | $SED -e s%$OCSHOME/packages/%%g`
@@ -342,51 +341,126 @@ case "$1" in
       opaltarget=""
       if [ "$1" = "-command" ]; then
         shift
-	opaltarget="$opaltarget $1"
-	shift
+        opaltarget="$opaltarget $1"
+        shift
       fi
       PATH=$OCSHOME/bin:$PATH; export PATH
       while [ -n "$1" ]
-	do
-	    SourceSpecs $1
-	    CheckRequireds
-	    case "$1" in
-		lib.*)
-		    opalcmd="ocs $LIBOCSFLAGS $opaltarget"
-		    CINCPATH="$CINCPATH $LIBINCLUDES"
-		    export CINCPATH
-		    $ECHO "Doing '$opalcmd' on library $1 ..."
-		    for d in $LIBSYSTEMS
-		    do
-		    echo "now in libsystem $d"
-		    if [ -n "$LIBPREOCSHOOK" ] ; then
-		      (cd $d; eval $LIBPREOCSHOOK)
-		    fi  
-		    (cd $d; $opalcmd); status=$?
-		    if [ $status -gt 0 ] ; then exit $status; fi
-		    done
-		    shift
-		    ;;
-		pkg.*)
-		    opalcmd="ocs $PKGOCSFLAGS $opaltarget"
-		    $ECHO "Doing '$opalcmd' on package $1 ..."
-		    if [ -n "$PKGPREOCSHOOK" ] ; then
-		      (cd $PKGBASE; eval $PKGPREOCSHOOK)
-		    fi  
-		    (cd $PKGBASE; $opalcmd); status=$?
-		    shift
-		    ;;
-		*)
-		    $ECHO "Don't know how to do '$opalcmd' with $1"
-		    exit 5
-		    ;;
+        do
+            SourceSpecs $1
+            CheckRequireds
+            case "$1" in
+                lib.*)
+                    opalcmd="ocs $LIBOCSFLAGS $opaltarget"
+                    CINCPATH="$CINCPATH $LIBINCLUDES"
+                    export CINCPATH
+                    $ECHO "Doing '$opalcmd' on library $1 ..."
+                    for d in $LIBSYSTEMS
+                    do
+                    echo "now in libsystem $d"
+                    if [ -n "$LIBPREOCSHOOK" ] ; then
+                      (cd $d; eval $LIBPREOCSHOOK)
+                    fi  
+                    (cd $d; $opalcmd); status=$?
+                    if [ $status -gt 0 ] ; then exit $status; fi
+                    done
+                    shift
+                    ;;
+                pkg.*)
+                    opalcmd="ocs $PKGOCSFLAGS $opaltarget"
+                    $ECHO "Doing '$opalcmd' on package $1 ..."
+                    if [ -n "$PKGPREOCSHOOK" ] ; then
+                      (cd $PKGBASE; eval $PKGPREOCSHOOK)
+                    fi  
+                    (cd $PKGBASE; $opalcmd); status=$?
+                    shift
+                    ;;
+                *)
+                    $ECHO "Don't know how to do '$opalcmd' with $1"
+                    exit 5
+                    ;;
             esac
-	    if [ $status -gt 0 ] ; then exit $status; fi
-	done
-	;;
+            if [ $status -gt 0 ] ; then exit $status; fi
+        done
+        ;;
+    update_inter)			# Basically only for opal_base, oc_oc1, oc_oc2, oc_shared.
+      shift
+      opaltarget=""
+      if [ "$1" = "-command" ]; then
+        shift
+        opaltarget="$opaltarget $1"
+        shift
+      fi
+      PATH=$OCSHOME/bin:$PATH; export PATH
+      while [ -n "$1" ]
+        do
+	    echo "BOOTING $1"
+            SourceSpecs $1
+            CheckRequireds
+            case "$1" in
+                lib.*)
+                    opalcmd="ocs $LIBOCSFLAGS $opaltarget"
+		    echo "OPALCMD $opalcmd"
+                    CINCPATH="$CINCPATH $LIBINCLUDES"
+                    export CINCPATH
+                    $ECHO "Doing '$opalcmd' on library $1 ..."
+                    for d in $LIBSYSTEMS
+                    do
+                        echo "now in libsystem $d"
+                        if [ -n "$LIBPREOCSHOOK" ] ; then
+                            (cd $d; eval $LIBPREOCSHOOK)
+                        fi
+                        (cd $d; rm -rf OCS; $opalcmd); status=$?
+                        if [ $status -gt 0 ] ; then exit $status; fi
+
+			# Now copy inter files to destination.
+			# This code is basically from genshlib.sh
+			sys=$d/OCS
+			echo "SYS $sys"
+			dest=$LIBDIR
+			echo "DEST $dest"
+                        structs="`( cd $sys; $LS *.sign.inter | \
+                                 $SED -e 's@\([^ ][^ ]*\)\.sign.inter@\1@')`"
+                           #       -e 's@BOOL@@' \
+                           #       -e 's@DENOTATION@@' \
+                           #       -e 's@ABORT@@' \
+                           # )`"
+echo "STRUCTS: $structs"
+			for s in $structs
+			do
+			    if [ ! "$sys/$s.sign.inter" = "$dest/$s.sign.inter" ]
+			    then
+				echo Copying $sys/$s.sign.inter
+				$RM -f $dest/$s.sign.inter
+				cp -f $sys/$s.sign.inter $dest
+				if [ -f $sys/$s.opt ]
+				then
+				    cp -f $sys/$s.opt $dest
+				fi
+				if [ -f $sys/$s.h ]
+				then
+				    cp -f $sys/$s.h $dest
+				fi
+				if [ -f $sys/$s.hc.h ]
+				then
+				    cp -f $sys/$s.hc.h $dest
+				fi
+			    fi
+			done
+                    done
+                    shift
+                    ;;
+                *)
+                    $ECHO "Don't know how to do '$opalcmd' with $1"
+                    exit 5
+                    ;;
+            esac
+            if [ $status -gt 0 ] ; then exit $status; fi
+      done
+      ;;
     *)
-	usage
-	exit 1
+        usage
+        exit 1
 esac
   
 exit 0
