*** empty log message ***

diff --git a/src/om/scripts/ocsadmin b/src/om/scripts/ocsadmin
--- a/src/om/scripts/ocsadmin
+++ b/src/om/scripts/ocsadmin
@@ -1,5 +1,5 @@
 #! /bin/sh
-# $Header: /home/florenz/opal/home_uebb_CVS/CVS/ocs/src/om/scripts/ocsadmin,v 1.11 2000-01-27 20:50:58 kd Exp $
+# $Header: /home/florenz/opal/home_uebb_CVS/CVS/ocs/src/om/scripts/ocsadmin,v 1.12 2000-06-07 20:35:57 kd Exp $
 
 ## initialise SHELL
 SHELL=/bin/sh
@@ -202,18 +202,28 @@ if [ "$1" = "init" ]; then
       fi
       shift
     else
-      mkdir $OCSHOME
-      ok=$?
-      if [ "$ok" != "0" ]; then
-	  echo "cannot create $OCSHOME"
-	  echo "use make reinstall for installation into existing directory"
-  	  exit 2
+      if [ ! -d "$OCSHOME" ]; then
+        mkdir $OCSHOME
+        ok=$?
+        if [ "$ok" != "0" ]; then
+	    echo "cannot create $OCSHOME"
+  	    exit 2
+        fi
+      else
+        if [ ! -w "$OCSHOME" ]; then
+          echo "$OCSHOME exists, but is not writeable"
+	  exit 2
+        fi
+	checkdir=`ls $OCSHOME`
+	if [ -n "$checkdir" ]; then
+	  echo "$OCSHOME is not empty. Use make reinstall"
+	  exit 2
+	fi
       fi
     fi
     SpecsDir=no
     for s in $OCSSPECS
     do
-	[ -f "$s/Specs.basic" ]
 	if [ -f "$s/Specs.basic" ]; then
 	    SpecsDir=$s
 	fi
@@ -226,7 +236,12 @@ if [ "$1" = "init" ]; then
 	echo "cannot find $OCSETC/gmake2sh"
 	exit 2
     fi
-    mkdir $OCSHOME/bin $OCSHOME/lib $OCSHOME/lib/opal_base $OCSHOME/lib/om $OCSHOME/lib/om/etc $OCSHOME/lib/om/specs $OCSHOME/lib/om/make $OCSHOME/packages $OCSHOME/man $OCSHOME/man/man1
+    for d in $OCSHOME/bin $OCSHOME/lib $OCSHOME/lib/opal_base $OCSHOME/lib/om $OCSHOME/lib/om/etc $OCSHOME/lib/om/specs $OCSHOME/lib/om/make $OCSHOME/packages $OCSHOME/man $OCSHOME/man/man1
+    do
+      if [ ! -d $d ] ; then
+        mkdir $d
+      fi
+    done
     cp $OCSADMIN $OCSHOME/bin
     cp $OCSSRC/lib/System/Commands/_ostart.c $OCSHOME/lib/opal_base
     cp $OCSETC/gmake2sh $OCSHOME/lib/om/etc
