GlobalRules.doc fuer leichtes Erstellen von Dokumentationen

diff --git a/src/om/make/GlobalRules b/src/om/make/GlobalRules
--- a/src/om/make/GlobalRules
+++ b/src/om/make/GlobalRules
@@ -1,5 +1,5 @@
-# Generic make rules for all OCS systems 
-# $Header: /home/florenz/opal/home_uebb_CVS/CVS/ocs/src/om/make/GlobalRules,v 1.1.1.1 1998-06-16 15:59:50 wg Exp $
+# Generic make rules for all OCS systems  -*- makefile -*-
+# $Header: /home/florenz/opal/home_uebb_CVS/CVS/ocs/src/om/make/GlobalRules,v 1.2 1998-10-12 18:31:40 kd Exp $
 
 OM_RULES_INCLUDED := yes
 
@@ -11,13 +11,13 @@ RERUNVARS :=	-f $(MAKEFILE)
 
 all:
 	@$(MAKE) $(RERUNVARS) RTARGET=all _subsystems _all
-	
+
 sub:
 	@$(MAKE) $(RERUNVARS) RTARGET=sub _realsubsystems _all
-	
+
 check:
 	@$(MAKE) $(RERUNVARS) RTARGET=check _subsystems _check
-	
+
 install:
 	@$(MAKE) $(RERUNVARS) RTARGET=install _subsystems _install
 
@@ -40,12 +40,45 @@ clean: _clean
 cleanall:
 	@$(MAKE) $(RERUNVARS) RTARGET=cleanall _subsystems clean
 
+cleanobj: _cleanobj
+
+
+cleanobjall:
+	@$(MAKE) $(RERUNVARS) RTARGET=cleanobjall _subsystems cleanobj
+
+texi:
+	@$(MAKE) $(RERUNVARS) RTARGET=texi _subsystems _texi
+
+thisdocall:
+	@$(MAKE) $(RERUNVARS) RTARGET=thisdocall _subsystems _thisdoc
+
+thisdoc: _thisdoc
+
+doc: html
+
+cleandoc: _cleandoc
+
+dvi: _dvi
+
+html: _html
+
+
+ifdef PROJECTROOT
+include $(OMLIBPATH)/GlobalRules.doc
+else
+_texi _cleandoc _dvi _html _thisdoc:
+	@$(ECHO) "+++ Cannot determine root directory of the project!"
+	@$(ECHO) "+++ add a line 'PROJECTROOT = ...' to the ProjectDefs or SysDefs file"
+	@$(ECHO) "+++ or define and export PROJECTROOT in the shell"
+	@exit 9
+endif	
+
 pack:
 	@$(MAKE) $(RERUNVARS) RTARGET=pack _pack _subsystems
 
 
-.PHONY: all sub install gen genall clean cleanall pack check
-.PRECIOUS: all sub install gen genall clean cleanall pack check
+.PHONY: all sub install gen genall clean cleanall cleanobj cleanobjall pack check doc cleandoc dvi html texi thisdoc thisdocall
+.PRECIOUS: all sub install gen genall clean cleanall cleanobj cleanobjall pack check doc cleandoc dvi html texi thisdoc thisdocall
 
 
 # Run MAKE with RTARGET on all SUBNODES
@@ -56,7 +89,7 @@ _subsystems:
 	do \
 	  $(ECHO) ">>>> Visiting subnode '$$i' making '$(RTARGET)' <<<<" ; \
 	  $(DATE); \
-	  ($(CD) $$i; $(MAKE) $(RERUNVARS) 'RTARGET=' $(RTARGET)) \
+	  ($(CD) $$i; $(MAKE) $(RERUNVARS) 'RTARGET=' $(RTARGET) 'SUBMAKE=sub' ) \
 					|| exit 2; \
 	done
 
@@ -68,7 +101,7 @@ _realsubsystems:
 	do \
 	  $(ECHO) ">>>> Visiting subsystem '$$i' making '$(RTARGET)' <<<<" ; \
 	  $(DATE); \
-	  ($(CD) $$i; $(MAKE) $(RERUNVARS) 'RTARGET=' $(RTARGET)) \
+	  ($(CD) $$i; $(MAKE) $(RERUNVARS) 'RTARGET=' $(RTARGET) 'SUBMAKE=sub' ) \
 					|| exit 2; \
 	done
 
