Skripte und Datien zum Einrichten und Durchführen eines Selbsttests

diff --git a/admin/selftest/selftest b/admin/selftest/selftest
--- a/admin/selftest/selftest
+++ b/admin/selftest/selftest
@@ -1,12 +1,11 @@
 #!/bin/sh
 
-# $Header: /home/florenz/opal/home_uebb_CVS/CVS/ocs/admin/selftest/selftest,v 1.2 1999-03-25 13:23:01 kd Exp $
+# $Header: /home/florenz/opal/home_uebb_CVS/CVS/ocs/admin/selftest/selftest,v 1.3 1999-09-10 14:34:57 kd Exp $
 
 # Script for booting & selftesting a new Opal compiler.
 
 # This script uses a checked-out source hierarchie 
-# suitable for `ocs' (obtained by `ors update') to
-# implement a bootstrap loop as follows.
+# suitable for `ocs'  to implement a bootstrap loop as follows.
 
 # At each iteration step, it compiles the library
 # and the compiler found under $TOCS/src/{oc,lib} with
@@ -22,23 +21,22 @@
 # process after cleaning up all derived objects.
 
 
-# NOTE. We should have used `ors' instead of `ocs', but
-# the permant retrieves on the source repository slow down
-# the net too much.
-
 # See also ProjectDefs.selftest
 
+# initial values for command line parameters
 nice=
 restart=no
 iter=3
+saveconf=no
+begintime=`date`
 
 id=`date +"%H-%d-%m"`
 
 while [ $# -ge 1 ] 
 do
   case $1 in
-    -update)
-      update=yes
+    -saveconf)
+      saveconf=yes
       shift
       ;;
     -nice) 
@@ -62,29 +60,19 @@ done
 
 if [ $# -ge 1 ]
 then
-  echo "usage: `basename $0` [ -update ] [ -nice ] [ -restart ] [ 1|2|...|9 ]"
+  echo "usage: `basename $0` [ -saveconf ] [ -nice ] [ -restart ] [ 1|2|...|9 ]"
   exit 255
 fi
 
 if [ -z "$TOCS" ]
 then
-  echo "You must define enverionemnt variable TOCS"
+  echo "You must define environment variable TOCS"
   exit 255
 fi
 
 OCSPROJECT=$TOCS/ProjectDefs.selftest
 export OCSPROJECT
 
-# update of source tree
-
-if [ "$update" = yes ]
-then
-  echo
-  echo "Updating sources"
-  echo
-  (cd $TOCS/src; ors update)
-
-fi
 
 # short test if sources are available
 
@@ -92,7 +80,7 @@ if [ ! -f $TOCS/src/oc/SysDefs ] || [ ! -f $TOCS/src/oc/oc1/SysDefs ] \
 	 || [ ! -f $TOCS/src/lib/SysDefs ]
 then
   echo "Probably not all sources around."
-  echo "Use \`ors update' or option -update to retrieve them."
+#  echo "Use \`ors update' or option -update to retrieve them."
 fi
 
 echo
@@ -147,6 +135,9 @@ do
   	echo "checking differences of oc1"
 	strip $TOCS/src/oc/oc1/driver/oc1
 	diff $TOCS/src/oc/oc1/driver/oc1 $TOCS/bin/oc1
+	ok1=$?
+  else
+    ok1=1
   fi 
   if [ -x $TOCS/bin/oc2 ] 
   then 
@@ -154,18 +145,26 @@ do
   	echo "checking differences of oc2"
 	strip $TOCS/src/oc/oc2/driver/oc2
 	diff $TOCS/src/oc/oc2/driver/oc2 $TOCS/bin/oc2
+	ok2=$?
+  else
+    ok2=1
   fi 
-#  saveconf="boot-$cnt-$id.tar.gz"
-#  echo "Saving configuration to $saveconf"
-  date
-#  ocsdirs="`find $TOCS/src -type d -name OCS -print`"
-#  if [ $last = yes ] 
-#  then
-#    tar cf - $TOCS/bin/oc1 $TOCS/bin/oc2 $TOCS/bin/genmake $TOCS/src/lib \
-#		$ocsdirs | gzip -9 > $saveconf
-#  else
-#    tar cf - $TOCS/src/lib $ocsdirs | gzip > $saveconf
-#  fi
+
+date
+
+if [ "$saveconf" = "yes" ]
+then
+  saveconf="boot-$cnt-$id.tar.gz"
+  echo "Saving configuration to $saveconf"
+  ocsdirs="`find $TOCS/src -type d -name OCS -print`"
+  if [ "$last" = "yes" ] 
+  then
+    tar cf - $TOCS/bin/oc1 $TOCS/bin/oc2 $TOCS/bin/genmake $TOCS/src/lib \
+		$ocsdirs | gzip -9 > $saveconf
+  else
+    tar cf - $TOCS/src/lib $ocsdirs | gzip > $saveconf
+  fi
+fi
   echo 
   echo "Installing new compiler"
   (cd $TOCS/src/oc/oc1/driver; ocs $ocsparam install) || exit 4
@@ -175,3 +174,15 @@ do
   cnt=`expr $cnt + 1`
 
 done
+
+endtime=`date`
+echo "Begin was:  $begintime"
+echo "Time now is:$endtime"
+
+if [ "$ok1" -gt 0 ] || [ "$ok2" -gt 0 ] ; then
+  echo "selftest failed!"
+  exit 1
+else
+  echo "selftest completed successfully!"
+  exit 0
+fi
